image: node:12.6.0
options:
  max-time: 20
pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run test
          - npm run build:pipelines
